package com.cucund.project.test.util;

import cn.hutool.json.JSON;
import com.cucund.project.tool.utils.json.JSONUtils;
import org.apache.commons.lang3.time.DateUtils;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.util.*;

public class SensitiveWord {
	
	private final WordTree tree = new WordTree();
	
	private final Set<ImportWord> keyWordSet = new HashSet<ImportWord>();
	
	private SensitiveWord() {
		
	}
	
	public static SensitiveWord init(){
		return new SensitiveWord();
	}
	
	public SensitiveWord addKeyWordSet(Set<ImportWord> keyWordSet) {
		this.keyWordSet.addAll(keyWordSet);
		build();
		return this;
	}
	
	public SensitiveWord build() {
		if(keyWordSet.isEmpty())
			throw new RuntimeException("无过滤关键词");
		//迭代keyWordSet
        Iterator<ImportWord> iterator = keyWordSet.iterator();
        while(iterator.hasNext()){
        	
        	ImportWord wordEntity = iterator.next();    //关键字
            String key = wordEntity.getWord();
            int level = wordEntity.getLevel();
            int score = wordEntity.getScore();
            Word node = null;
            for(int i = 0 ; i < key.length() ; i++){
                char keyChar = key.charAt(i);       //转换成char型
                if(node == null) {//首次进入从  树中获取关键词对象
                	node = tree.addNode(keyChar);
                	continue;
                }
                Set<Word> list = node.getNextNode();//获取 下一个节点
                boolean flag = false;
                if(list == null||list.isEmpty()) {//如果未有下一个节点
                	list = new HashSet<Word>();
                	node.setNextNode(list);
                	flag = true;
                }else {
                	boolean loopFlag = false;
                	for (Word word : list) {//查询是否存在下一个节点
                		if(keyChar == word.getWord()) {
                			node = word;
                			loopFlag = true;
                			break;
                		}
                	}
                	if(!loopFlag) {
                		flag = !loopFlag;
                	}
				}
                if(flag) {
                	node = new Word(keyChar,0,false);
                	list.add(node);
                }
                if(key.length()-1 == i) {//如果是最后一个字符直接结束
                	node.setEnd(true);
                	node.setLevel(level);
                	node.setScore(score);
                	break;
                }
            }
        }
		return this;
	}
	
	/**
	 * 执行敏感词过滤器
	 * @param txt 文本内容
	 * @param beginIndex	开始节点
	 * @return
	 */
    public SensitiveResponse filter(String txt,int beginIndex) {
		if(keyWordSet.isEmpty())
			throw new RuntimeException("无过滤关键词");
        SensitiveResponse response = new SensitiveResponse(txt);//过滤 返回对象
        for(int i = beginIndex; i < txt.length() ; i++){//循环开始
        	char word = txt.charAt(i);	//当前循环字节
        	Word nowWord = tree.get(word);	//从词典树中获取是否存在
            if(nowWord!=null) {	//存在执行
                int x = 0;	//内循环次数初始化
                while (true) {
                	int y = i + (++x);//内循环字符坐标
                	if(y==txt.length())//是否是文本最后一个字
                		break;
					char nextWord = txt.charAt(y);//当前内循环字节
					nowWord = checkNext(nowWord,nextWord);//是否在词典树中存在
                	if(nowWord == null)//无 , 跳出内循环
                		break;
                	if(nowWord.isEnd()) {//是最后一个  加入过滤结果集
                		int score = nowWord.getScore();
                		int level = nowWord.getLevel();
                		SensitiveResult data = new SensitiveResult(i,y);//过滤结果创建
						response.setIndex(level, score, data);//塞入结果集
            			break;
                	}
    			}
            }else{     //不存在，直接返回
                continue;
            }
        }
		return response;
    }

    private Word checkNext(Word nowMap, char word) {
    	if(nowMap.getNextNode()==null) {
    		return null;
    	}
    	for (Word nowWord : nowMap.getNextNode()) {
    		if(nowWord.getWord() == word)
    			return nowWord;
		}
		return null;
	}

	public static void main(String[] args) {
		Set<ImportWord> set = new HashSet<ImportWord>();
		List<String> words = getLine("C://Users//Administrator//Desktop//新建文件夹//mgck-master/暴恐词库.txt");
		for (String word : words) {
			set.add(new ImportWord(word, 1,1));
		}
		words = getLine("C://Users//Administrator//Desktop//新建文件夹//mgck-master/反动词库.txt");
		for (String word : words) {
			set.add(new ImportWord(word, 1,1));
		}
		words = getLine("C://Users//Administrator//Desktop//新建文件夹//mgck-master/民生词库.txt");
		for (String word : words) {
			set.add(new ImportWord(word, 1,1));
		}
		words = getLine("C://Users//Administrator//Desktop//新建文件夹//mgck-master/其他词库.txt");
		for (String word : words) {
			set.add(new ImportWord(word, 1,1));
		}
		words = getLine("C://Users//Administrator//Desktop//新建文件夹//mgck-master/色情词库.txt");
		for (String word : words) {
			set.add(new ImportWord(word, 1,1));
		}
		words = getLine("C://Users//Administrator//Desktop//新建文件夹//mgck-master/贪腐词库.txt");
		for (String word : words) {
			set.add(new ImportWord(word, 1,1));
		}
		
		System.out.println("敏感词词库长度:"+set.size());
		SensitiveWord word = SensitiveWord.init().addKeyWordSet(set);
		String txt = "[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "oapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[大法弟子[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法轮[aoognqafv[abn[pfeoa[法o功[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "oapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "oapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[soapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcnabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabcoapsfpoanpvpasodabcf[aoognqafv[abn[pfeoa[snabc"
				+ "法o功";
		long start = new Date().getTime();
		SensitiveResponse filter = word.filter(txt,0);
		long end = new Date().getTime();
		System.out.println("共计耗时:"+(end - start)+" ms,文本长度: "+txt.length()+",过滤结果:"+filter.getLenght());
		for (SensitiveResultSet setx : filter.getList()) {
			System.out.println("级别:"+setx.getLevel()+",得分"+setx.getScore());
		}
		try {
			System.out.println(JSONUtils.obj2json(filter.getList()));
		} catch (Exception e) {
		}
	}

	private static List<String> getLine(String filename) {
		List<String> words = new ArrayList<>();
		try {
            File file = new File(filename);
            FileInputStream fis = new FileInputStream(file);
            BufferedReader br = new BufferedReader(new InputStreamReader(fis,"GBK"));
            String line;
            while ((line = br.readLine()) != null) {
            	words.add(line);
            }
            fis.close();
 
        } catch (Exception e) {
            e.printStackTrace();
        }
		return words;
	}
}
